### ISSUE TITLE
[ReactDevTools] components are not loaded

### ISSUE THREAD

**Issue by spamshaker** [MarshallOfSound/electron-devtools-installer#238]
On Mac M1 OS Ventura when used installer I am getting the following error

"electron-devtools-installer": "^3.2.0",
"electron": "23.1.1"

```
(node:75950) ExtensionLoadWarning: Warnings loading extension at /Users/user/Library/Application Support/app/extensions/fmkadmapgofadopljbjfkapdkoienihi:
  Permission 'scripting' is unknown or URL pattern is malformed.

[75950:0326/172543.650797:ERROR:CONSOLE(2)] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[75950:0326/172543.650825:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)
[75950:0326/172545.408171:ERROR:extensions_browser_client.cc(62)] Extension Error:
  OTR:     false
  Level:   2
  Source:  chrome-extension://poocdgihabcgkndohblokpkdlnkmlkdj/build/background.js
  Message: Uncaught TypeError: Cannot read properties of undefined (reading 'registerContentScripts')
  ID:      poocdgihabcgkndohblokpkdlnkmlkdj
  Type:    RuntimeError
  Context: chrome-extension://poocdgihabcgkndohblokpkdlnkmlkdj/build/background.js
  Stack Trace: 
    {
      Line:     107
      Column:   1
      URL:      chrome-extension://poocdgihabcgkndohblokpkdlnkmlkdj/build/background.js
      Function: (anonymous function)
    }
[75950:0326/172548.361243:ERROR:CONSOLE(2)] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[75950:0326/172548.361280:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)
[75950:0326/172549.919597:ERROR:extensions_browser_client.cc(62)] Extension Error:
  OTR:     false
  Level:   2
  Source:  chrome-extension://poocdgihabcgkndohblokpkdlnkmlkdj/build/background.js
  Message: Uncaught TypeError: Cannot read properties of undefined (reading 'registerContentScripts')
  ID:      poocdgihabcgkndohblokpkdlnkmlkdj
  Type:    RuntimeError
  Context: chrome-extension://poocdgihabcgkndohblokpkdlnkmlkdj/build/background.js
  Stack Trace: 
    {
      Line:     107
      Column:   1
      URL:      chrome-extension://poocdgihabcgkndohblokpkdlnkmlkdj/build/background.js
      Function: (anonymous function)
    }
2023-03-26 17:37:35.472 Electron[75950:28284964] +[CATransaction synchronize] called within transaction
2023-03-26 17:37:35.563 Electron[75950:28284964] +[CATransaction synchronize] called within transaction
```

the extension is loaded in browser view, but in Devtools -> Components tab, it says 

Loading React Element Tree...
If this seems stuck, please follow the [troubleshooting instructions](https://github.com/facebook/react/blob/main/packages/react-devtools/README.md#the-react-tab-shows-no-components).

The extension works fine in Chrome browser.

what could be wrong?

**Comment by spamshaker** [comment]
ok seems it is the electron issue which differs than chrome. So the extension won't work due to electron has not exposed chrome.scripting in the api
https://www.electronjs.org/docs/latest/api/extensions#supported-extensions-apis
maybe this should be mentioned in README that the https://github.com/facebook/react/tree/main/packages/react-devtools-extensions/chrome extension won't work

**Comment by xupea** [comment]
@spamshaker hope this repo ease your pain: https://github.com/xupea/electron-devtools-installer

**Comment by jonluca** [comment]
That version seems to be having issues with electron 24.

Also that repo redirects CRX requests to the developers domain, instead of downloading directly from the chrome webstore. (see here https://github.com/xupea/electron-devtools-installer/blob/master/src/downloadChromeExtension.ts#L24)

<img width="1062" alt="capture 2023-04-06 at 1 22 26 PM" src="https://user-images.githubusercontent.com/13029040/230486273-9450f04b-c448-469d-81f2-79bb79b99d90.png">


I published https://www.npmjs.com/package/electron-extension-installer to fix that (source code [here](https://github.com/jonluca/electron-extension-installer))


```typescript
import { installExtension, REACT_DEVELOPER_TOOLS } from "electron-extension-installer";

app.on("ready", async () => {
  await installExtension(REACT_DEVELOPER_TOOLS, {
    loadExtensionOptions: {
      allowFileAccess: true,
    },
  });
});
```

**Comment by unzld** [comment]
> That version seems to be having issues with electron 24.
> 
> ~Also that repo redirects CRX requests to the developers domain, instead of downloading directly from the chrome webstore. (see here https://github.com/xupea/electron-devtools-installer/blob/master/src/downloadChromeExtension.ts#L24)~ - I now realize this is required, because google doesn't let you download historical chrome versions, unfortunately
> 
> <img alt="capture 2023-04-06 at 1 22 26 PM" width="1062" src="https://user-images.githubusercontent.com/13029040/230486273-9450f04b-c448-469d-81f2-79bb79b99d90.png">
> 
> I published https://www.npmjs.com/package/electron-extension-installer to fix that (source code [here](https://github.com/jonluca/electron-extension-installer))
> 
> ```ts
> import { installExtension, REACT_DEVELOPER_TOOLS } from "electron-extension-installer";
> 
> app.on("ready", async () => {
>   await installExtension(REACT_DEVELOPER_TOOLS, {
>     loadExtensionOptions: {
>       allowFileAccess: true,
>     },
>   });
> });
> ```

I'm still getting errors while using yours, but this time they're different from OP. 

```
[1] [149237:0414/043621.834038:ERROR:CONSOLE(2)] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[1] [149237:0414/043621.834072:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)
[1] [149237:0414/043624.487576:ERROR:CONSOLE(2)] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[1] [149237:0414/043624.487647:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)
```

**Comment by syabro** [comment]
@unzld  same here...

**Comment by jonluca** [comment]
AFAICT that issue is internal, when calling load extension, and needs to fixed from electrons side.

**Comment by MarcelFinkbeiner** [comment]
Same for me (vite,vue3,ts,electron,VUEJS3_DEVTOOLS).

**Comment by jcharnley** [comment]
> That version seems to be having issues with electron 24.
> 
> ~Also that repo redirects CRX requests to the developers domain, instead of downloading directly from the chrome webstore. (see here https://github.com/xupea/electron-devtools-installer/blob/master/src/downloadChromeExtension.ts#L24)~ - I now realize this is required, because google doesn't let you download historical chrome versions, unfortunately
> 
> <img alt="capture 2023-04-06 at 1 22 26 PM" width="1062" src="https://user-images.githubusercontent.com/13029040/230486273-9450f04b-c448-469d-81f2-79bb79b99d90.png">
> 
> I published https://www.npmjs.com/package/electron-extension-installer to fix that (source code [here](https://github.com/jonluca/electron-extension-installer))
> 
> ```ts
> import { installExtension, REACT_DEVELOPER_TOOLS } from "electron-extension-installer";
> 
> app.on("ready", async () => {
>   await installExtension(REACT_DEVELOPER_TOOLS, {
>     loadExtensionOptions: {
>       allowFileAccess: true,
>     },
>   });
> });
> ```

this is the only solution that works for me, great work on the npm package

**Comment by geek4teck** [comment]
> That version seems to be having issues with electron 24.
> 
> ~Also that repo redirects CRX requests to the developers domain, instead of downloading directly from the chrome webstore. (see here https://github.com/xupea/electron-devtools-installer/blob/master/src/downloadChromeExtension.ts#L24)~ - I now realize this is required, because google doesn't let you download historical chrome versions, unfortunately
> 
> <img alt="capture 2023-04-06 at 1 22 26 PM" width="1062" src="https://user-images.githubusercontent.com/13029040/230486273-9450f04b-c448-469d-81f2-79bb79b99d90.png">
> 
> I published https://www.npmjs.com/package/electron-extension-installer to fix that (source code [here](https://github.com/jonluca/electron-extension-installer))
> 
> ```ts
> import { installExtension, REACT_DEVELOPER_TOOLS } from "electron-extension-installer";
> 
> app.on("ready", async () => {
>   await installExtension(REACT_DEVELOPER_TOOLS, {
>     loadExtensionOptions: {
>       allowFileAccess: true,
>     },
>   });
> });
> ```

Works great for me. Here is a copy of main.ts file if someone wants to replace it to make it work for them ❤️ 

`/* eslint global-require: off, no-console: off, promise/always-return: off */

/**
 * This module executes inside of electron's main process. You can start
 * electron renderer process from here and communicate with the other processes
 * through IPC.
 *
 * When running `npm run build` or `npm run build:main`, this file is compiled to
 * `./src/main.js` using webpack. This gives us some performance wins.
 */
import path from 'path';
import { app, BrowserWindow, shell, ipcMain } from 'electron';
import { autoUpdater } from 'electron-updater';
import log from 'electron-log';
import {
  installExtension,
  REACT_DEVELOPER_TOOLS,
} from 'electron-extension-installer';
import MenuBuilder from './menu';
import { resolveHtmlPath } from './util';

class AppUpdater {
  constructor() {
    log.transports.file.level = 'info';
    autoUpdater.logger = log;
    autoUpdater.checkForUpdatesAndNotify();
  }
}

let mainWindow: BrowserWindow | null = null;

ipcMain.on('ipc-example', async (event, arg) => {
  const msgTemplate = (pingPong: string) => `IPC test: ${pingPong}`;
  console.log(msgTemplate(arg));
  event.reply('ipc-example', msgTemplate('pong'));
});

if (process.env.NODE_ENV === 'production') {
  const sourceMapSupport = require('source-map-support');
  sourceMapSupport.install();
}

const isDebug =
  process.env.NODE_ENV === 'development' || process.env.DEBUG_PROD === 'true';

if (isDebug) {
  require('electron-debug')();
}

// const installExtensions = async () => {
//   const installer = require('electron-devtools-installer');
//   const forceDownload = !!process.env.UPGRADE_EXTENSIONS;
//   const extensions = ['REACT_DEVELOPER_TOOLS', 'REDUX_DEVTOOLS'];

//   return installer
//     .default(
//       extensions.map((name) => installer[name]),
//       forceDownload,
//     )
//     .catch(console.log);
// };

const createWindow = async () => {
  // if (isDebug) {
  //   await installExtensions();
  // }

  const RESOURCES_PATH = app.isPackaged
    ? path.join(process.resourcesPath, 'assets')
    : path.join(__dirname, '../../assets');

  const getAssetPath = (...paths: string[]): string => {
    return path.join(RESOURCES_PATH, ...paths);
  };

  mainWindow = new BrowserWindow({
    show: false,
    width: 1024,
    height: 728,
    icon: getAssetPath('icon.png'),
    webPreferences: {
      preload: app.isPackaged
        ? path.join(__dirname, 'preload.js')
        : path.join(__dirname, '../../.erb/dll/preload.js'),
    },
  });

  mainWindow.loadURL(resolveHtmlPath('index.html'));

  mainWindow.on('ready-to-show', () => {
    if (!mainWindow) {
      throw new Error('"mainWindow" is not defined');
    }
    if (process.env.START_MINIMIZED) {
      mainWindow.minimize();
    } else {
      mainWindow.show();
    }
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });

  const menuBuilder = new MenuBuilder(mainWindow);
  menuBuilder.buildMenu();

  // Open urls in the user's browser
  mainWindow.webContents.setWindowOpenHandler((edata) => {
    shell.openExternal(edata.url);
    return { action: 'deny' };
  });

  // Remove this if your app does not use auto updates
  // eslint-disable-next-line
  new AppUpdater();
};

/**
 * Add event listeners...
 */

app.on('window-all-closed', () => {
  // Respect the OSX convention of having the application in memory even
  // after all windows have been closed
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app
  .whenReady()
  .then(async () => {
    await installExtension(REACT_DEVELOPER_TOOLS, {
      loadExtensionOptions: {
        allowFileAccess: true,
      },
    });
    createWindow();
    app.on('activate', () => {
      // On macOS it's common to re-create a window in the app when the
      // dock icon is clicked and there are no other windows open.
      if (mainWindow === null) createWindow();
    });
  })
  .catch(console.log);
`

**Comment by Stanzilla** [comment]
@MarshallOfSound any plans to update this?

**Comment by nikinikinico** [comment]
I used electron-extension-installer but another promble occured, [39252:0415/173432.902:ERROR:CONSOLE(2)] "Electron renderer.bundle.js script failed to run", source: node:electron/js2c/renderer_init (2) ， does any body have the same promble?

**Comment by tomhervieu9** [comment]
> I used electron-extension-installer but another promble occured, [39252:0415/173432.902:ERROR:CONSOLE(2)] "Electron renderer.bundle.js script failed to run", source: node:electron/js2c/renderer_init (2) ， does any body have the same promble?

I am facing the same issue. According the the publisher of electron-extensions-installer, it seems the problem is from electron's side. https://github.com/MarshallOfSound/electron-devtools-installer/issues/238#issuecomment-1538349985 . It could be that updating to a more recent version of electron could fix this or the error just needs to keep getting handled until the bug gets fixed (if it was reported at all).

Still, big shout out to @jonluca for publishing the package.

**Comment by danthegoodman** [comment]
After some digging around, I found the following things:
1. React looks for `__REACT_DEVTOOLS_GLOBAL_HOOK__` with a `checkDCE` function. (HMR tooling also sets up this global but without that property, which threw off my debugging a little bit)
2. The extension injects this global into every page through the use of a `background: {serviceWorker: ...}` property in the manifest.
3. Electron doesn't seem to init this service worker until after the devtools are opened up for the first time.

So to work around this in my own app, I setup this function and call it before I setup my app window:
```javascript
async function loadDevtools() {
  const edi = await import('electron-devtools-installer');
  const installExtension = edi.default.default;
  await installExtension(edi.REDUX_DEVTOOLS);
  await installExtension(edi.REACT_DEVELOPER_TOOLS);

  // hack because extension service workers aren't loaded until after first launch
  const win = new BrowserWindow({
    show: false,
    webPreferences: { devTools: true },
  });
  await win.loadURL('about:blank');
  win.webContents.openDevTools({ mode: 'detach', activate: false });
  await new Promise<void>((resolve, reject) => {
    let checksLeft = 300;
    const interval = setInterval(() => {
      const all = session.defaultSession.serviceWorkers.getAllRunning();
      if (Object.keys(all).length > 0) {
        clearInterval(interval);
        resolve();
      } else {
        checksLeft -= 1;
        if (checksLeft <= 0) {
          clearInterval(interval);
          reject(new Error('react dev tools failed to load a service worker'));
        }
      }
    }, 10);
  });
  win.close();
}
```

**Comment by Stanzilla** [comment]
> After some digging around, I found the following things:
> 
> 1. React looks for `__REACT_DEVTOOLS_GLOBAL_HOOK__` with a `checkDCE` function. (HMR tooling also sets up this global but without that property, which threw off my debugging a little bit)
> 2. The extension injects this global into every page through the use of a `background: {serviceWorker: ...}` property in the manifest.
> 3. Electron doesn't seem to init this service worker until after the devtools are opened up for the first time.
> 
> So to work around this in my own app, I setup this function and call it before I setup my app window:
> 
> ```js
> async function loadDevtools() {
>   const edi = await import('electron-devtools-installer');
>   const installExtension = edi.default.default;
>   await installExtension(edi.REDUX_DEVTOOLS);
>   await installExtension(edi.REACT_DEVELOPER_TOOLS);
> 
>   // hack because extension service workers aren't loaded until after first launch
>   const win = new BrowserWindow({
>     show: false,
>     webPreferences: { devTools: true },
>   });
>   await win.loadURL('about:blank');
>   win.webContents.openDevTools({ mode: 'detach', activate: false });
>   await new Promise<void>((resolve, reject) => {
>     let checksLeft = 300;
>     const interval = setInterval(() => {
>       const all = session.defaultSession.serviceWorkers.getAllRunning();
>       if (Object.keys(all).length > 0) {
>         clearInterval(interval);
>         resolve();
>       } else {
>         checksLeft -= 1;
>         if (checksLeft <= 0) {
>           clearInterval(interval);
>           reject(new Error('react dev tools failed to load a service worker'));
>         }
>       }
>     }, 10);
>   });
>   win.close();
> }
> ```

that errors with 

```[{
	"resource": "/Users/stan/projects/personal/wago-app/src/main/main.ts",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'default' does not exist on type '(extensionReference: string | ExtensionReference | (string | ExtensionReference)[], options?: boolean | ExtensionOptions | undefined) => Promise<...>'.",
	"source": "ts",
	"startLineNumber": 146,
	"startColumn": 40,
	"endLineNumber": 146,
	"endColumn": 47
}]```

for 

>   const installExtension = edi.default.default;

**Comment by danthegoodman** [comment]
> When exactly are you calling your function?
```js
app.whenRead().then(main).catch(console.error);
async function main(){
  if (IS_DEV) {
    await loadDevTools();
  }
  await launchApp();
}
```

> I assume you wanted const installExtension = edi.default; but that sadly does not work here either.

I wrestled with the import a little bit. I'm using ESM imports, `@swc-core/cli` to compile my code and `typescript` to just do type linting. In various iterations, I just clobbered the offending import with `//@ts-ignore` statements and poked and prodded with the import statement until I got it to run.

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
